### ISSUE TITLE
Change the title of the app

### ISSUE THREAD

**Issue by Jomagene** [kaliacad/mostvisitedarticle#117]
### Description

Le titre de la version actuelle est Vite + React.

### Comportement Attendu

Il serait préférable de le changer pour quelque chose qui reflète le titre de l'application. Exemple : "Articles les plus visités" ou "Most visited articles".

### Comportement Actuel

Le titre actuel est "Vite + React" qui ne décrit pas précisément le but ou le contenu de l'application.

### Captures d'écran (si applicable)

![Illustration du problème](https://i.imgur.com/I6Z0lpJ.png)

### Type de Problème

- [ ] Bug
- [ ] Demande de Fonctionnalité
- [x] Amélioration
- [ ] Question
- [ ] Autre (veuillez spécifier)

### Liste de Vérification

- [x] Ce problème n'est pas un doublon.
- [x] Toutes les informations requises sont incluses.

**Comment by sparrow690** [comment]
je veux trevailler sur cet issue
