### ISSUE TITLE
En tant que developpeur , je souhaite creer un composant reutilisable pour afficher le resultat sous forme d'item dans un tableau

### ISSUE THREAD

**Issue by CREDO23** [kaliacad/mostvisitedarticle#14]

**Comment by firminfinva** [comment]
@CREDO23 @JoeMakuta I'm working on this one

**Comment by jedidia17** [comment]
@CREDO23 En tant que développeur, il est important de créer des composants réutilisables pour simplifier le code et améliorer la maintenabilité. Cela permet de gagner du temps et de réduire les erreurs en évitant de réécrire le même code à plusieurs reprises.

**Comment by Ger-Cub** [comment]
Je souhaite travailler sur cette issue
