### ISSUE TITLE
As Thietry, I want to see skeleton of result items when the request is in a loading state

### ISSUE THREAD

**Issue by Bam92** [kaliacad/mostvisitedarticle#152]

**Comment by land-bit** [comment]
@Bam92, je prend l'issue

**Comment by CREDO23** [comment]
@land-bit, what is the state of this issue ?

**Comment by land-bit** [comment]
@CREDO23 , c’est pas moi le créateur de l’issue, mais je crois que @Bam92 , voulais que l’utilisateur vois le squeleton en attendant que les résultats sont chargé. 

Pour l’instant, l’application reste en suspens, on ne voit pas si les données sont traités ou pas
