### ISSUE TITLE
Créer un pied de page

### ISSUE THREAD

**Issue by CREDO23** [kaliacad/mostvisitedarticle#16]
En tant que développeur, je veux créer un composant de pied de page pour afficher les informations et les liens de bas de page (voir modèle).

![Image](https://github.com/kaliacad/wikidataqueriIA/assets/14941675/6be74647-b5f0-4363-8ee9-ffca821b23c5)

**Comment by francetambwe** [comment]
je voudrais travailler sur cet issue

**Comment by jedidia17** [comment]
@CREDO23  @Bam92 Creating a Website Footer:
