### ISSUE TITLE
Fix layout on top africa menu

### ISSUE THREAD

**Issue by Bam92** [kaliacad/mostvisitedarticle#179]
Current layout

![Image](https://github.com/kaliacad/mostvisitedarticle/assets/14941675/483a168e-19ba-4d64-a294-f487440534f4)

Expected
<img width="1792" alt="Screenshot 2024-06-08 at 22 29 31" src="https://github.com/kaliacad/mostvisitedarticle/assets/14941675/613c4b68-7f12-414d-adf7-c1f2eb211b99">

**Comment by land-bit** [comment]
@Bam92 , je voulais prendre cette issue mais je remarque que c'est déjà resolue.

Veillez le fermer s'il vous plait
