### ISSUE TITLE
Proposer une date par défaut dans le formulaire se trouvant sur la page d'accueil

### ISSUE THREAD

**Issue by Tacite243** [kaliacad/mostvisitedarticle#192]
### Description

Décrivez brièvement le problème ou l'amélioration.

### Comportement Attendu

Décrivez ce que vous attendiez qu'il se passe.

### Comportement Actuel

Décrivez ce qui s'est réellement passé.

### Captures d'écran (si applicable)

Incluez des captures d'écran ou des GIFs s'ils aident à expliquer le problème.

### Type de Problème

- [ ] Bug
- [ ] Demande de Fonctionnalité
- [ ] Amélioration
- [ ] Question
- [ ] Autre (veuillez spécifier)

### Liste de Vérification

- [ ] Ce problème n'est pas un doublon.
- [ ] Toutes les informations requises sont incluses.

Merci !

**Comment by Tacite243** [comment]
Je travaille sur cette issue, veuillez me l'assigner s'il vous plait ! @Bam92 @CREDO23 @JoeMakuta @Delord-Nzanzu

**Comment by JoeMakuta** [comment]
This issue is refered to #120

**Comment by JoeMakuta** [comment]
#120
