### ISSUE TITLE
Use Toast notification instead of popup when coping permanent link

### ISSUE THREAD

**Issue by Bam92** [kaliacad/mostvisitedarticle#206]
### Description

When we click on the permanent link button, a popup displays on the screen.

### Comportement Attendu
Unobstructive notification 
### Comportement Actuel

Décrivez ce qui s'est réellement passé.
Obstructive notification 

### Type de Problème

- [ ] Bug
- [ ] Demande de Fonctionnalité
- [x] Amélioration
- [ ] Question
- [ ] Autre (veuillez spécifier)

### Liste de Vérification

- [x] Ce problème n'est pas un doublon.
- [x] Toutes les informations requises sont incluses.

**Comment by land-bit** [comment]
@Bam92, je prend l'issue
