### ISSUE TITLE
Fix the infinite loading state in the page view when searching for a misspelled article title

### ISSUE THREAD

**Issue by CREDO23** [kaliacad/mostvisitedarticle#212]

**Comment by siddharthisrani** [comment]
Hii @Bam92 Could you please assign this issue to me?

**Comment by siddharthisrani** [comment]
Hii @Bam92  I have completed the task regarding the infinite loading issue and have opened a pull request.Please take a moment to review the PR at your convenience. I appreciate any feedback you may have.

**Comment by CREDO23** [comment]
Your PR was merged @siddharthisrani
