### ISSUE TITLE
filter articles and get true articles

### ISSUE THREAD

**Issue by blessingtutka** [kaliacad/mostvisitedarticle#219]
### Description

Décrivez brièvement le problème ou l'amélioration.
Il y a des articles qui ne sont pas vraiment des articles comme les pages principales, les spéciales et autres. Il faut les filtrer et obtenir de vrais articles.

### Comportement Attendu

Décrivez ce que vous attendiez qu'il se passe.

### Comportement Actuel

Décrivez ce qui s'est réellement passé.

### Captures d'écran (si applicable)

Incluez des captures d'écran ou des GIFs s'ils aident à expliquer le problème.

### Type de Problème

- [ ] Bug
- [ ] Demande de Fonctionnalité
- [x] Amélioration
- [ ] Question
- [ ] Autre (veuillez spécifier)

### Liste de Vérification

- [ ] Ce problème n'est pas un doublon.
- [ ] Toutes les informations requises sont incluses.

Merci !

**Comment by Bam92** [comment]
Merci beaucoup, @blessingtutka pour cet issue. Je propose de mettre une case à cocher comme [ici](https://pageviews.wmcloud.org/topviews/?project=fr.wikipedia.org&platform=all-access&date=last-month&excludes=) (afficher uniquement les pages de l'espace principal).
