### ISSUE TITLE
Improve pagination

### ISSUE THREAD

**Issue by Bam92** [kaliacad/mostvisitedarticle#221]
Display 9 or 12 items per page.

Pagination should look similar to this [file](https://cdn.prod.website-files.com/63fc977c14aaea404dce4439/6579b130fa3d1aa5ce9aaef4_img4.webp)

**Comment by Yashop181** [comment]
Hi @Bam92 ,

I'd like to work on improving the pagination as outlined in issue #221. My plan is to display 9 or 12 items per page and ensure the pagination UI matches the design specified in the file provided.

I'll implement the following improvements:

-Update the articlesPerPage to either 9 or 12.
-Enhance the pagination component to include left and right arrows with page numbers in between for easy navigation.
-Ensure the UI is responsive and aligns with the design specifications.
-Here are before and after screenshots to illustrate the changes:

Before:
![Screenshot (1158)](https://github.com/user-attachments/assets/69286626-322e-41a8-a706-79e034e7783b)

After:
![Screenshot (1159)](https://github.com/user-attachments/assets/7cb3bc04-4413-4197-a7cf-f1bc8e08afab)

Please let me know if you have any additional requirements or suggestions before I start.

**Comment by Bam92** [comment]
Hi @Yashop181,

Thank you so much for your contribution. Do submit your PR.

**Comment by Yashop181** [comment]
Hi @Bam92 ,

I have successfully created a pull request and completed the task. Please review and let me know if there are any changes needed.

Thank you!

**Comment by Bam92** [comment]
Hi @Yashop181: thank you for your code. I've merged. Should you have time, feel free to pick up another issue or create issues.
