### ISSUE TITLE
Move router code from main.jsx to rounters/index.jsx

### ISSUE THREAD

**Issue by Bam92** [kaliacad/mostvisitedarticle#223]
### Description

The code for router is in `main.jsx` and nothing in `routers/`

### Comportement Attendu

Import router in `main.jsx`

### Comportement Actuel

N/A

### Type de Problème

- [ ] Bug
- [ ] Demande de Fonctionnalité
- [X] Amélioration
- [ ] Question
- [ ] Autre (veuillez spécifier)

**Comment by AACHAL2303PATIL** [comment]
I would like to work on this issue please assign it to me.

**Comment by siddharthisrani** [comment]
Hii @Bam92 Could you please assign me this issue?

**Comment by Bam92** [comment]
@siddharthisrani can you take another issue? I've assigned it to @AACHAL2303PATIL.
