### ISSUE TITLE
[Improvement] Top Africa | List view should display more items that gallery view

### ISSUE THREAD

**Issue by CREDO23** [kaliacad/mostvisitedarticle#233]
We only display 9 items in the gallery view, but we can display more in the list view since we should have sufficient space !
![Screenshot from 2024-07-27 12-09-46](https://github.com/user-attachments/assets/8c373138-9133-41fc-ae7f-69ebd3f95336)

**Comment by LokeshPatil-loki** [comment]
Hi @CREDO23,
I have created a fix for this issue. The changes have been made in pull request #235.
