### ISSUE TITLE
[Design] Add background to the chart in page views

### ISSUE THREAD

**Issue by Bam92** [kaliacad/mostvisitedarticle#238]
It's difficult to clearly view data of the chart.

<img width="1792" alt="Screenshot 2024-07-31 at 13 09 50" src="https://github.com/user-attachments/assets/5d49a9a0-2e62-4fab-8a2f-ec473407ea46">

The request is to add a white border-radius background color around the chart

**Comment by AACHAL2303PATIL** [comment]
Please assign it to me I would like to work on it.
