### ISSUE TITLE
En tant que Thierry, je veux etre à mesure de telecharger les resultats sous format JSON ou CSV

### ISSUE THREAD

**Issue by CREDO23** [kaliacad/mostvisitedarticle#24]
![Image](https://github.com/kaliacad/mostvisitedarticle/assets/14941675/8a1f7bee-2eae-4cec-8ec1-a1aecd3cc242)

**Comment by birego** [comment]
je voudrai travailler sur cet issue #24  @Delord-Nzanzu  @CREDO23 @Bam92 @JoeMakuta

**Comment by birego** [comment]
Pour l'instant j'ai crée un composant reutilisable qui exporte en PDF les elements d'une balise @CREDO23 @GloireMutaliko21
