### ISSUE TITLE
Pick-liste pays et bouton de recherche 

### ISSUE THREAD

**Issue by ItVal** [kaliacad/mostvisitedarticle#61]
### Description

Décrivez brièvement le problème ou l'amélioration.

### Comportement Attendu

Décrivez ce que vous attendiez qu'il se passe.

### Comportement Actuel

Décrivez ce qui s'est réellement passé.

### Captures d'écran (si applicable)

Incluez des captures d'écran ou des GIFs s'ils aident à expliquer le problème.

### Type de Problème

- [ ] Bug
- [ ] Demande de Fonctionnalité
- [ ] Amélioration
- [ ] Question
- [ ] Autre (veuillez spécifier)

### Liste de Vérification

- [ ] Ce problème n'est pas un doublon.
- [ ] Toutes les informations requises sont incluses.

Merci !

**Comment by ItVal** [comment]
Description
Pick list où l'utilisateur va choisir les pays ainsi que le bouton rechercher

Comportement Attendu
Après avoir cliqué sur le bouton rechercher, qu'on puisse avoir le résultat attendu 

Comportement Actuel
RAS

Captures d'écran (si applicable)
Incluez des captures d'écran ou des GIFs s'ils aident à expliquer le problème.

Type de Problème
 Bug
 Demande de Fonctionnalité
 Amélioration
 Question
 Autre (veuillez spécifier)
Liste de Vérification
 Ce problème n'est pas un doublon.
 Toutes les informations requises sont incluses.
Merci !

**Comment by blessingtutka** [comment]
I want to work on this
@CREDO23 @JoeMakuta
