### ISSUE TITLE
Rendre les donnée de l'API dans le card Article

### ISSUE THREAD

**Issue by GloireMutaliko21** [kaliacad/mostvisitedarticle#80]
Dans ce tâche : 
- Rendre le composant ArticleCard réutilisable
- Afficher les données actuelles dans le card
![image](https://github.com/kaliacad/mostvisitedarticle/assets/86450367/777a4fad-d73b-4e50-9c89-84cad897d187)
Dans l'image ci-dessous, il y a la liste des articles qui doivent être affichées dans des cards (en flex)
![image](https://github.com/kaliacad/mostvisitedarticle/assets/86450367/082ad54e-0654-46a9-adc9-3b80ea6fbb5b)

Nous voulons donc aussi améliorer le composant ArticleCard pourqu'il affiche également le nombre de "vu"

**Comment by firminfinva** [comment]
i'm working on it @GloireMutaliko21  @JoeMakuta @CREDO23
