### ISSUE TITLE
Ajouter un titre et une favicone

### ISSUE THREAD

**Issue by Bam92** [kaliacad/mostvisitedarticle#81]
Emi - Voir la liste des articles les plus visités par pays

**Comment by jedidia17** [comment]
@Bam92 Ajouter un titre et une favicone

**Comment by Jomagene** [comment]
@jedidia17 Le titre n'a pas été effectif, juste la favicon. Je viens d'ouvrir une issue pour cela, vu que celle-ci est censée close. Travailles-y s'il te plaît.
