### ISSUE TITLE
Ajout bons liens sur footer

### ISSUE THREAD

**Issue by ItVal** [kaliacad/mostvisitedarticle#85]
### Description
Documentation : doit pointer sur la page meta de la documentation de l'application
Report an issue : sur les issues de l'application
Feedback : sur la page de discussion meta de la documentation 

Décrivez brièvement le problème ou l'amélioration.

### Comportement Attendu

Décrivez ce que vous attendiez qu'il se passe.
Redirection sur les bons liens
### Comportement Actuel
Mauvais lien
Décrivez ce qui s'est réellement passé.

### Captures d'écran (si applicable)

Incluez des captures d'écran ou des GIFs s'ils aident à expliquer le problème.

### Type de Problème

- [ ] Bug
- [ ] Demande de Fonctionnalité
- [ ] Amélioration
- [ ] Question
- [ ] Autre (veuillez spécifier)

### Liste de Vérification

- [ ] Ce problème n'est pas un doublon.
- [ ] Toutes les informations requises sont incluses.

Merci !

**Comment by francetambwe** [comment]
i'm working in this issue @JoeMakuta @CREDO23
