### ISSUE TITLE
En tant que developpeur je veux me connecter à l'API

### ISSUE THREAD

**Issue by CREDO23** [kaliacad/mostvisitedarticle#9]

**Comment by blessingtutka** [comment]
J'aimerais demander si pour réaliser cela on doit mettre a disposition les elements des api en utilisant du js. Si c'est le cas j'aimerais travailler sur ce issue. Je veux svp les ressources pour l'API.
@CREDO23

**Comment by Cedric921** [comment]
Done

**Comment by CREDO23** [comment]
@blessingtutka, tu peux ajouter la logique qu'il y a dans le fichier articleList.js sur la main page ?
